server:
  port: 8080
  servlet:
    session:
      timeout: 1800 # 세션 만료 1800초(30분)

property:
  api:
    end-point: /api

spring:
  output:
    ansi:
      enabled: always
  banner:
    location: classpath:config/banner.txt
  datasource:
    url: ENC(o3bICGexKsW8QjJaKICeVdSwHoS9els4JVcZ/mTq++pO5dRXHqAuJ+Q7JUHBV5xIGoR57uiDQ8P/yGwI8S6gjS2L3qHrNhSJt2K7jePOlHJmv2ANcP+CZQ==)
    username: ENC(BEYfyGd2VYgPakaFrkfbRPPON988cPhK9yJe0bFDqQA=)
    password: ENC(lDTXfXjpcXGSGHGi9OzrhRrkbt/Wq9XDK2a2rKXUelc=)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  mail:
    username: ENC(csROf5c32ROUdJpsMe1i73NvA7wV7lTpmtfYwDImCrTexmZBZi06j4OQLePPI7kW)
    password: ENC(+0qbHK9dC10/wJnTUCvl9geLVRmkKtGfiHIjAvinrahX5OT/9M9RsA==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# logging
logging:
  config: src/main/resources/config/log4j2.xml