server:
  port: 8080

property:
  api:
    end-point: /api

spring:
  output:
    ansi:
      enabled: always
  banner:
    location: classpath:config/banner.txt
  datasource:
    url: jdbc:mysql://132.145.88.154:3306/planE?characterEncoding=utf8
    username: planeapp
    password: New1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: ENC(csROf5c32ROUdJpsMe1i73NvA7wV7lTpmtfYwDImCrTexmZBZi06j4OQLePPI7kW)
    password: ENC(+0qbHK9dC10/wJnTUCvl9geLVRmkKtGfiHIjAvinrahX5OT/9M9RsA==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true